[package]
authors = ["panicbit <panicbit.dev@gmail.com>"]
name = "av"
version = "0.1.0"

[dependencies]
bitflags = "0.7.0"
error-chain = "0.9.0"
lazy_static = "0.2.2"
libc = "0.2.19"

[dependencies.av_sys]
path = "av_sys"

[workspace]
