[package]
authors = ["panicbit <panicbit.dev@gmail.com>"]
build = "build.rs"
name = "av"
version = "0.1.0"

[[bin]]
name = "av"

[build-dependencies]
libbindgen = "0.1.5"

[dependencies]
lazy_static = "0.2.2"
libc = "0.2.19"
