[package]
authors = ["panicbit <panicbit.dev@gmail.com>"]
name = "av"
version = "0.1.0"

[[bin]]
name = "av"

[dependencies]
av_sys = { path = "av_sys" }
libc = "0.2.19"
lazy_static = "0.2.2"

[workspace]
