use ffi::*;

bitflags! {
    pub flags ChannelLayout: u64 {
        const CHANNEL_LAYOUT_NATIVE            = AV_CH_LAYOUT_NATIVE            as u64,
        const CHANNEL_LAYOUT_MONO              = AV_CH_LAYOUT_MONO              as u64,
        const CHANNEL_LAYOUT_STEREO            = AV_CH_LAYOUT_STEREO            as u64,
        const CHANNEL_LAYOUT_2POINT1           = AV_CH_LAYOUT_2POINT1           as u64,
        const CHANNEL_LAYOUT_2_1               = AV_CH_LAYOUT_2_1               as u64,
        const CHANNEL_LAYOUT_SURROUND          = AV_CH_LAYOUT_SURROUND          as u64,
        const CHANNEL_LAYOUT_3POINT1           = AV_CH_LAYOUT_3POINT1           as u64,
        const CHANNEL_LAYOUT_4POINT0           = AV_CH_LAYOUT_4POINT0           as u64,
        const CHANNEL_LAYOUT_4POINT1           = AV_CH_LAYOUT_4POINT1           as u64,
        const CHANNEL_LAYOUT_2_2               = AV_CH_LAYOUT_2_2               as u64,
        const CHANNEL_LAYOUT_QUAD              = AV_CH_LAYOUT_QUAD              as u64,
        const CHANNEL_LAYOUT_5POINT0           = AV_CH_LAYOUT_5POINT0           as u64,
        const CHANNEL_LAYOUT_5POINT1           = AV_CH_LAYOUT_5POINT1           as u64,
        const CHANNEL_LAYOUT_5POINT0_BACK      = AV_CH_LAYOUT_5POINT0_BACK      as u64,
        const CHANNEL_LAYOUT_5POINT1_BACK      = AV_CH_LAYOUT_5POINT1_BACK      as u64,
        const CHANNEL_LAYOUT_6POINT0           = AV_CH_LAYOUT_6POINT0           as u64,
        const CHANNEL_LAYOUT_6POINT0_FRONT     = AV_CH_LAYOUT_6POINT0_FRONT     as u64,
        const CHANNEL_LAYOUT_HEXAGONAL         = AV_CH_LAYOUT_HEXAGONAL         as u64,
        const CHANNEL_LAYOUT_6POINT1           = AV_CH_LAYOUT_6POINT1           as u64,
        const CHANNEL_LAYOUT_6POINT1_BACK      = AV_CH_LAYOUT_6POINT1_BACK      as u64,
        const CHANNEL_LAYOUT_6POINT1_FRONT     = AV_CH_LAYOUT_6POINT1_FRONT     as u64,
        const CHANNEL_LAYOUT_7POINT0           = AV_CH_LAYOUT_7POINT0           as u64,
        const CHANNEL_LAYOUT_7POINT0_FRONT     = AV_CH_LAYOUT_7POINT0_FRONT     as u64,
        const CHANNEL_LAYOUT_7POINT1           = AV_CH_LAYOUT_7POINT1           as u64,
        const CHANNEL_LAYOUT_7POINT1_WIDE      = AV_CH_LAYOUT_7POINT1_WIDE      as u64,
        const CHANNEL_LAYOUT_7POINT1_WIDE_BACK = AV_CH_LAYOUT_7POINT1_WIDE_BACK as u64,
        const CHANNEL_LAYOUT_OCTAGONAL         = AV_CH_LAYOUT_OCTAGONAL         as u64,
        const CHANNEL_LAYOUT_HEXADECAGONAL     = AV_CH_LAYOUT_HEXADECAGONAL     as u64,
        const CHANNEL_LAYOUT_STEREO_DOWNMIX    = AV_CH_LAYOUT_STEREO_DOWNMIX    as u64,
    }
}
