[package]
authors = ["panicbit <panicbit.dev@gmail.com>"]
build = "build.rs"
name = "av_sys"
version = "0.1.0"

[build-dependencies]
bindgen = "0.23.*"
syn = { version = "0.11", features = ["full", "parsing", "printing"] }
quote = "0.3"

[dependencies]
